[[speakers]]
name = "福野 泰介"
furi = "ふくの たいすけ"
title = "セッション調整中"
description = "調整中"
profile = """
# 略歴
1978年11月8日石川県生まれ。国立福井工業高等専門学校電子情報工学科を卒業後、2000年に有限会社シャフトを設立しCTOに就任。2001年に有限会社ユーエヌアイ研究所を設立、代表取締役社長に就任。2003年5月に株式会社jig.jpを設立し代表取締役社長に就任（現任）。
2016年に内閣官房情報通信技術（IT）総合戦略室が任命する「オープンデータ伝道師（8名）」のひとり

# 紹介
小学3年生の時、何度でも作り直せるプログラミングの世界に出会い、開発言語をBASIC、アセンブラ、C言語と変えながらソフト作りに熱中する。福井高専に在学中、研究会やアルバイトでソフト開発に携わり、自分が開発したものを人に使ってもらう喜びを知る。卒業後、フリープログラマーをしながら起業を考える。2つの会社の創業を経て、現在の株式会社jig.jpを設立。当時モバイルサイトしか見られなかった携帯電話向けに、パソコン用サイトを閲覧可能とする世界初のダウンロード型のフルブラウザ『jigブラウザ』を開発。より豊かな社会のモデルを探るため、本店があり、在住している福井県鯖江市で、こどもやシニア向けのプログラミング講座、自治体オープンデータ「データシティ鯖江」とそれを活用する団体「Code for Sabae」、首都圏の起業家と交流するITイベントなどを手がけている。また、高専生の更なる活躍に期待しており、全国の高専からのインターン受け入れや講演会、「Code for KOSEN」などを通じて、後輩のバックアップに取り組んでいる。
"""
image = "/img/2017_fukuno@2x.jpg"
github = "taisukef"
twitter = "taisukef"
facebook = "taisuke.fukuno"
tags = ["IoT", "IchigoJam"]

  [[speakers.links]]
  name = "福野泰介の一日一創"
  href = "http://fukuno.jig.jp"


[[speakers]]
name = "山本 学"
furi = "やまもと まなぶ"
title = "myThings使ったIoTによる地域課題解決"
description = "調整中"
tags = ["myThings"]
image = "/img/2017_yamamoto@2x.jpg"

[[speakers]]
name = "寺田 佳央"
furi = "てらだ よしお"
title = "セッション調整中"
description = "調整中"
tags = ["Microsoft", "Java", "広島"]


[[speakers]]
name = "元木 昭宏"
furi = "もとき あきひろ"
title = "セッション調整中"
description = "調整中"
image = "/img/2017_motoki@2x.jpg"
profile = """
2015年8月、ハッカソンという単語も知らずにハッカソンに参加し、ICTをツールとしたオープンイノベーションに目覚める。以来、アイデアソン／ハッカソンのみならず各種イベントに参加することでICTコミュニティを作りながら、広島の存在感増幅を目指して活動中。また、17年間楽しんでいるサイクリングについても、ICTのチカラを借りてイノベーションを起こす事を企み中。
"""
facebook = "akihiro.motoki.5"
tags = ["ミドル", "広島"]

  [[speakers.oraganizatinos]]
    name = "NPO法人 瀬戸内サイクルメディア"
    href = "http://npo-scm.wixsite.com/setouchi"
  [[speakers.oraganizatinos]]
    name = "一般社団法人 HMCN（Hiroshima Motion Control Network）"
    href = "https://hmcn.doorkeeper.jp/"
  [[speakers.oraganizatinos]]
    name = "マツダ株式会社コネクティビティ企画"

  [[speakers.links]]
    name = "ミドル×IT　50代からのスマホアプリ開発 @IT"
    href = "http://www.atmarkit.co.jp/ait/articles/1606/08/news009.html"

  [[speakers.sessions]]
    name = "次世代自動車ビジネス研究会 「コネクティビティーによる顧客体験の変革」"
    href = "http://techon.nikkeibp.co.jp/at/cp/16/car2025/"
  [[speakers.sessions]]
    name = "KDDI∞Labo2015"
    href = "https://www.pref.hiroshima.lg.jp/site/innovation/kddi1216.html"


[[speakers]]
name = "花谷 美香"
furi = "はなたに みか"
title = "子どもプログラミングとドリームマップ"
description = "調整中"
profile = """
電機メーカー勤務を経てパソコンインストラクターになり、県内私立大学や専門学校の非常勤講師、企業研修、その他官・民主催のパソコン講習の講師となる。
2016年3月より子どもプログラミング教室　Dream Tech Schoolを開校
現在　牛田、古田台、光明学園、舟入、宇品、広島YMCA学園の６教室で展開中。
また、光明学園、YMCA国際幼児園、なぎさ公園小学校にプログラミング授業を企画・提案し、実施することにより、子どもたちのより良い未来のために奮闘するかたわら、一般社団法人ドリームマップ普及協会の認定ドリマ講師として、小・中・高等学校等でドリームマップ授業を実施中。
"""
tags = ["子どもプログラミング", "広島"]

  [[speakers.oraganizatinos]]
    name = "株式会社ハッピーちゃい夢 代表取締役"
    href = "http://www.dream-tech.jp/company/"

[[speakers]]
name = "薬師神 裕樹"
furi = "やくしじん ゆうき"
title = "セッション調整中"
description = "調整中"
tags = ["UX", "広島"]
