[[speakers]]
name = "花谷 美香"
furi = "はなたに みか"
title = "子どもプログラミングとドリームマップ"
position = "株式会社ハッピーちゃい夢 代表取締役"
profile = """
"電機メーカー勤務を経てパソコンインストラクターになり、県内私立大学や専門学校の非常勤講師、企業研修、その他官・民主催のパソコン講習の講師となる。
2016年3月より子どもプログラミング教室　Dream Tech Schoolを開校
現在　牛田、古田台、光明学園、舟入、宇品、広島YMCA学園の６教室で展開中。
また、光明学園、YMCA国際幼児園、なぎさ公園小学校にプログラミング授業を企画・提案し、実施することにより、子どもたちのより良い未来のために奮闘するかたわら、一般社団法人ドリームマップ普及協会の認定ドリマ講師として、小・中・高等学校等でドリームマップ授業を実施中。"
"""
description = ""
tags = ["子どもプログラミング"]

[[speakers]]
name = "てらだ よしお"
furi = "てらだ よしお"
